### ISSUE TITLE
Fullscreen without cropping

### ISSUE THREAD

**Issue by Archonw** [Geektoolkit/Dynaframe3#11] opened 2020-09-27 14:07 UTC
Hallo, as you told in the video the fullscreen crops images to fit the screen totally. Is it possiblt to have black boarders at the sides so that no material will be cropped? I hope you understand what i want you to tell...

**Comment by qwksilver** [comment] 2020-09-30 03:54
these options are being addressed with issue #8

**Comment by Geektoolkit** [comment] 2020-09-30 09:40
Agreed, issue 8 covers this, and the plan is to offer settings for this 'overall' with thoughts in the future for 'per folder' settings or possibly per file. Closing this as it's a duplicate of 8 so that the workitems are cleaned up.  This is on my short list to get done, and I appreciate the feedback!

**Closed by Geektoolkit** 2020-09-30 09:40 UTC
